In [2]:
#1. Import the numpy package under the name np
import numpy as np

#2. Print the numpy version and the configuration
print(np.__version__)
print(np.show_config())


1.26.1
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140680530736656
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.1
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.3
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  hos

In [4]:
#3. Create a null vector of size 10
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
#4. How to find the memory size of any array
memory_size = null_vector.nbytes
print(f"Memory size of the array is: {memory_size} bytes")

Memory size of the array is: 80 bytes


In [10]:
#5. How to get the documentation of the numpy add function from the command line
# You can use `np.info()` or `np.lookfor()`
print(np.info(np.add))
# Alternatively
print(np.lookfor('add'))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [21]:
#6. Create a null vector of size 10 but the fifth value which is 1
null_vector[4] = 1
print(null_vector)
print()

#7. Create a vector with values ranging from 10 to 49
vector_10_to_49 = np.arange(10, 50)
print(vector_10_to_49)
print()

#8. Reverse a vector
reversed_vector = np.flip(vector_10_to_49)
print(reversed_vector)
print()

#9. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape((3, 3))
print(matrix_3x3)
print()

#10. Find indices of non-zero elements from [1,2,0,0,4,0]
nonzero_indices = np.nonzero([1, 2, 0, 0, 4, 0])
print(nonzero_indices)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

(array([0, 1, 4]),)


In [13]:
# 11. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("11. Identity Matrix:\n", identity_matrix)

# 12. Create a 3x3x3 array with random values
random_3d_array = np.random.random((3, 3, 3))
print("\n12. 3x3x3 Random Array:\n", random_3d_array)

# 13. Create a 10x10 array with random values and find the min and max
random_10x10_array = np.random.random((10, 10))
min_value = np.min(random_10x10_array)
max_value = np.max(random_10x10_array)
print("\n13. 10x10 Random Array:\n", random_10x10_array)
print("   Min Value:", min_value)
print("   Max Value:", max_value)


11. Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

12. 3x3x3 Random Array:
 [[[0.12387436 0.0577069  0.05708132]
  [0.09315736 0.99037711 0.69322208]
  [0.37087724 0.51581049 0.39448182]]

 [[0.50395356 0.62886907 0.12878626]
  [0.67999023 0.72565498 0.81729295]
  [0.00967262 0.93616099 0.80329641]]

 [[0.95601257 0.31462786 0.59929952]
  [0.34942774 0.94472054 0.53837832]
  [0.72368138 0.66612549 0.0884994 ]]]

13. 10x10 Random Array:
 [[0.76920848 0.11499343 0.63129137 0.00170774 0.39995898 0.6973706
  0.16845871 0.43181944 0.16090689 0.70180238]
 [0.08317612 0.40938556 0.13657357 0.86685425 0.95787077 0.63474914
  0.90891469 0.90618764 0.85496481 0.70045486]
 [0.09318953 0.67535998 0.49986013 0.49554515 0.84675134 0.07390117
  0.79712619 0.23087896 0.22553808 0.07660046]
 [0.67860859 0.6608219  0.51964057 0.55169362 0.55243606 0.23287021
  0.32797739 0.70323207 0.30563893 0.38666151]
 [0.741664   0.56893351 0.72207892 0.22648304 0.77170723 0.1909077
  0.72365247 0.64031956 

In [18]:
# 14. Create a random vector of size 30 and find the mean value
random_vector = np.random.random(30)
mean_value = np.mean(random_vector)
print("\n14. Random Vector:\n", random_vector)
print("   Mean Value:", mean_value)

# 15. Create a 2d array with 1 on the border and 0 inside
border_array = np.ones((7, 7))
border_array[1:-1, 1:-1] = 0
print("\n15. 2D Array with Border:\n", border_array)

# 16. Add a border (filled with 0's) around an existing array
existing_array = np.ones((3, 3))
bordered_array = np.pad(existing_array, pad_width=1, mode='constant', constant_values=0)
print("\n16. Array with Border:\n", bordered_array)

# 17. Results of the given expressions
print('\n17. Result of the given expression:')
result_1 = 0 * np.nan
result_2 = np.nan == np.nan
result_3 = np.inf > np.nan
result_4 = np.nan - np.nan
result_5 = np.nan in set([np.nan])
result_6 = 0.3 == 3 *0.1
print("\n17. Results of Expressions:")
print("   0 * np.nan =", result_1)
print("   np.nan == np.nan =", result_2)
print("   np.inf > np.nan =", result_3)
print("   np.nan - np.nan =", result_4)
print("   np.nan in set([np.nan]) =", result_5)
print("   0.3 == 3 * 0.1 =", result_6)




14. Random Vector:
 [0.00793271 0.56030942 0.03202107 0.96666996 0.90907158 0.26773593
 0.01462326 0.33913998 0.59717147 0.3269136  0.71289085 0.2359651
 0.0771311  0.54251331 0.70128934 0.98404897 0.69645059 0.64983387
 0.74512319 0.84398914 0.69158649 0.78714058 0.86501657 0.54277163
 0.73242302 0.26825831 0.52319255 0.42479804 0.900752   0.08271253]
   Mean Value: 0.5343158734875753

15. 2D Array with Border:
 [[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]

16. Array with Border:
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]

17. Result of the given expression:

17. Results of Expressions:
   0 * np.nan = nan
   np.nan == np.nan = False
   np.inf > np.nan = False
   np.nan - np.nan = nan
   np.nan in set([np.nan]) = True
   0.3 == 3 * 0.1 = False


In [25]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
diagonal_matrix = np.diag(1 + np.arange(4), k=-1)
print("18. Matrix Below Diagonal:\n", diagonal_matrix)

# 19. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard_matrix = np.zeros((8, 8), dtype=int)
checkerboard_matrix[1::2, ::2] = 1
checkerboard_matrix[::2, 1::2] = 1
print("\n19. Checkerboard Matrix:\n", checkerboard_matrix)

# 20. Index (x, y, z) of the 100th element in a (6,7,8) shape array
array_shape = (6, 7, 8)
index_100th_element = np.unravel_index(100, array_shape)
print("\n20. Index of 100th Element in (6,7,8) array:", index_100th_element)

18. Matrix Below Diagonal:
 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]

19. Checkerboard Matrix:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

20. Index of 100th Element in (6,7,8) array: (1, 5, 4)


In [29]:
import numpy as np

# 21. Create a checkerboard 8x8 matrix using the tile function
checkerboard = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print("\n21.Checkerboard 8x8 matrix:\n", checkerboard)

# 22. Normalize a 5x5 random matrix
random_matrix = np.random.random((5, 5))
normalized_matrix = (random_matrix - np.mean(random_matrix)) / np.std(random_matrix)
print("\n22. Normalized 5x5 random matrix:\n", normalized_matrix)
print()

# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color_dtype = np.dtype([('R', np.ubyte, 1), ('G', np.ubyte, 1), ('B', np.ubyte, 1), ('A', np.ubyte, 1)])
print("\n23. Custom dtype for RGBA color:\n", color_dtype)

# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
matrix_a = np.random.random((5, 3))
matrix_b = np.random.random((3, 2))
matrix_product = np.dot(matrix_a, matrix_b)
print("24. Matrix product (5x3) * (3x2):\n", matrix_product)
print()

# 25. Given a 1D array, negate all elements which are between 3 and 8, in place.
array_1d = np.arange(11)
array_1d[(3 < array_1d) & (array_1d < 8)] *= -1
print("25. Negate elements between 3 and 8:\n", array_1d)



21.Checkerboard 8x8 matrix:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

22. Normalized 5x5 random matrix:
 [[ 0.16541009 -2.12209469  0.84215839 -0.73939463  0.77277309]
 [-0.6649255  -0.58919589  0.97015903 -1.13838379 -0.97327211]
 [ 1.59816255 -0.38598795 -1.23971206  1.4796511  -0.64705421]
 [-0.25261602  1.0050051  -1.19002266 -0.69246518  0.68364756]
 [-0.46849752  1.03331792  0.69156204  1.58626973  0.2755056 ]]


23. Custom dtype for RGBA color:
 [('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]
24. Matrix product (5x3) * (3x2):
 [[0.79946749 1.27901589]
 [0.88751517 1.08272844]
 [0.76196563 1.22748713]
 [0.26840363 0.42841577]
 [0.64839938 0.74433554]]

25. Negate elements between 3 and 8:
 [ 0  1  2  3 -4 -5 -6 -7  8  9 10]


/tmp/ipykernel_4858/3156307591.py:14: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color_dtype = np.dtype([('R', np.ubyte, 1), ('G', np.ubyte, 1), ('B', np.ubyte, 1), ('A', np.ubyte, 1)])


In [31]:
# 26. What is the output of the following script?
print("\n26. Output of the script:")
print(sum(range(5), -1))  # Output: 9
from numpy import *
print(sum(range(5), -1))  # Output: 10

# 27. Consider an integer vector Z, which of these expressions are legal?
Z = np.arange(5)
print("\n27. Legal expressions:")
print(Z ** Z)   
print(2 << Z >> 2)  
print(Z < -Z)    
print(1j * Z)    
print(Z / 1 / 1)  
# print(Z < Z > Z)  

# 28. What are the result of the following expressions?
print("\n28. Results of the expressions:")
print(np.array(0) / np.array(0))  
print(np.array(0) // np.array(0)) 
print(np.array([np.nan]).astype(int).astype(float))  

# 29. How to round away from zero a float array?
float_array = np.random.uniform(-10, 10, 5)
rounded_array = np.copysign(np.ceil(np.abs(float_array)), float_array)
print("\n29. Rounded array away from zero:")
print(rounded_array)

# 30. How to find common values between two arrays?
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])
common_values = np.intersect1d(array1, array2)
print("\n30. Common values between two arrays:")
print(common_values)



26. Output of the script:
10
10

27. Legal expressions:
[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]

28. Results of the expressions:
nan
0
[-9.22337204e+18]

29. Rounded array away from zero:
[10. -1.  5.  6.  8.]

30. Common values between two arrays:
[3 4 5]


/tmp/ipykernel_4858/1918682361.py:19: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_4858/1918682361.py:20: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_4858/1918682361.py:21: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [37]:
import numpy as np
import warnings

# 31. How to ignore all numpy warnings (not recommended)?
answer = warnings.filterwarnings("ignore", category=np.VisibleDeprecationWarning)
print("31. answer:\n", answer)
# 32. Is the following expression true?
result = np.sqrt(-1) == np.emath.sqrt(-1)
print("32. ", result)
# Explanation: NumPy's sqrt returns nan for negative inputs, but np.emath.sqrt returns a complex number.

# 33. How to get the dates of yesterday, today and tomorrow?
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')
print("33:  Yesterday:", yesterday, "Today:", today, "Tomorrow:", tomorrow)

# 34. How to get all the dates corresponding to the month of July 2016?
dates_july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print("34. dates_july_2016:", dates_july_2016)

# 35. How to compute ((A+B)*(-A/2)) in place (without copy)?
A = np.ones(3)
B = np.ones(3) * 2
np.multiply(A + B, -A / 2, out=A)
print("35. ", A)

# 36. Extract the integer part of a random array of positive numbers using 4 different methods
random_array = np.random.uniform(0, 10, 5)
method1 = random_array.astype(int)
method2 = np.floor(random_array)
method3 = np.ceil(random_array) - 1
method4 = np.trunc(random_array)
print("36. Original Array:", random_array)
print("Method 1:", method1)
print("Method 2:", method2)
print("Method 3:", method3)
print("Method 4:", method4)

# 37. Create a 5x5 matrix with row values ranging from 0 to 4
matrix_5x5 = np.zeros((5, 5)) + np.arange(5)
print("37: ", matrix_5x5)

# 38. Consider a generator function that generates 10 integers and use it to build an array
def generator_function():
    for i in range(10):
        yield i

array_from_generator = np.fromiter(generator_function(), dtype=int)
print("38. array_from_generator\n", array_from_generator)

# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded
vector_excluded = np.linspace(0, 1, 12)[1:-1]
print("39. ", vector_excluded)

# 40. Create a random vector of size 10 and sort it
random_vector = np.random.random(10)
sorted_vector = np.sort(random_vector)
print("40: Random Vector:", random_vector)
print("Sorted Vector:", sorted_vector)


31. answer:
 None
32.  False
33:  Yesterday: 2024-02-06 Today: 2024-02-07 Tomorrow: 2024-02-08
34. dates_july_2016: ['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']
35.  [-1.5 -1.5 -1.5]
36. Original Array: [4.76461119 5.77862956 1.67428637 0.08365289 4.4166981 ]
Method 1: [4 5 1 0 4]
Method 2: [4. 5. 1. 0. 4.]
Method 3: [4. 5. 1. 0. 4.]
Method 4: [4. 5. 1. 0. 4.]
37:  [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
38. array_from_generator
 [0 1 2 3 4 5 6 7 8 9]
39.  [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
40: Rando

/tmp/ipykernel_4858/2579678042.py:8: RuntimeWarning: invalid value encountered in sqrt
  result = np.sqrt(-1) == np.emath.sqrt(-1)


In [40]:
import numpy as np

# 41. Sum a small array faster than np.sum
arr = np.random.rand(1000)
sum_fast = np.einsum('i->', arr)

# 42. Check if two random arrays A and B are equal
A = np.random.rand(5, 5)
B = np.random.rand(5, 5)
are_equal = np.array_equal(A, B)

# 43. Make an array immutable (read-only)
immutable_arr = np.random.rand(3, 3)
immutable_arr.flags.writeable = False

# 44. Convert cartesian coordinates to polar coordinates
cartesian_coords = np.random.random((10, 2))
x, y = cartesian_coords[:, 0], cartesian_coords[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

# 45. Replace the maximum value in a random vector of size 10 by 0
random_vector = np.random.rand(10)
random_vector[random_vector.argmax()] = 0

# 46. Create a structured array with x and y coordinates covering [0,1]x[0,1]
structured_arr = np.zeros((10, 10), [('x', float), ('y', float)])
structured_arr['x'], structured_arr['y'] = np.meshgrid(np.linspace(0, 1, 10), np.linspace(0, 1, 10))

# 47. Construct the Cauchy matrix C
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)

# 48. Print the min and max representable values for each numpy scalar type
for dtype in [np.int8, np.int32, np.int64]:
    np.iinfo(dtype).min
    np.iinfo(dtype).max

# 49. Print all values of an array
arr_to_print = np.random.rand(3, 3)

# 50. Find the closest value to a given scalar in a vector
vector = np.random.rand(10)
scalar = 0.3
closest_value = vector[np.abs(vector - scalar).argmin()]

# Print results
print(f"41. Sum Fast: {sum_fast}")
print(f"42. Are A and B equal? {are_equal}")
print(f"43. Immutable Array: {immutable_arr}")
print(f"44. Polar Coordinates:\nR: {r}\nTheta: {theta}")
print(f"45. Random Vector with Max Replaced: {random_vector}")
print(f"46. Structured Array:\n{structured_arr}")
print(f"47. Cauchy Matrix:\n{C}")
print(f"48. Min and Max values for integers:\n{np.iinfo(np.int8)}, {np.iinfo(np.int32)}, {np.iinfo(np.int64)}")
print(f"49. Array to Print:\n{arr_to_print}")
print(f"50. Closest Value to {scalar}: {closest_value}")


41. Sum Fast: 497.31237355418983
42. Are A and B equal? False
43. Immutable Array: [[0.6929198  0.66758488 0.25417052]
 [0.8006119  0.9908693  0.68466023]
 [0.69763402 0.74515382 0.45377246]]
44. Polar Coordinates:
R: [1.32267574 0.99141182 0.94848635 0.64472474 0.87846978 0.76254361
 0.19976245 0.84733282 0.5040248  0.70239157]
Theta: [0.85343223 0.16815721 0.54711881 0.22685548 0.20646727 1.37831264
 0.49378495 0.243669   0.81922073 1.02008309]
45. Random Vector with Max Replaced: [0.32121742 0.12325748 0.04931985 0.12823625 0.78075407 0.40082417
 0.         0.75812236 0.23488111 0.14577355]
46. Structured Array:
[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.4444444

In [47]:
import numpy as np

# 51. Create a structured array representing a position (x,y) and a color (r,g,b)
position_color = np.zeros(3, dtype=[('position', [('x', float), ('y', float)]), ('color', [('r', int), ('g', int), ('b', int)])])
print("51.\n", position_color)

# 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances
random_vector = np.random.random((100, 2))
distances = np.sqrt(np.sum((random_vector - random_vector[:, np.newaxis])**2, axis=-1))
print("52.\n",distances)

# 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
float_array = np.array([1.5, 2.7, 3.9], dtype=np.float32)
float_array = float_array.view(np.int32)
print("53.\n",float_array)

# # 54. How to read the following file?
# data = np.genfromtxt('file.txt', delimiter=',')
# print("54.\n",data)

# 55. What is the equivalent of enumerate for numpy arrays?
array = np.array([1, 2, 3, 4, 5])
for index, value in np.ndenumerate(array):
    print("55.\n",index, value)

# 56. Generate a generic 2D Gaussian-like array
x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
gaussian = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print("56.\n",gaussian)

# 57. How to randomly place p elements in a 2D array?
p = 5
array_2d = np.zeros((10, 10))
np.put(array_2d, np.random.choice(range(10*10), p, replace=False), 1)
print("57.\n",array_2d)

# 58. Subtract the mean of each row of a matrix
matrix = np.random.rand(5, 5)
mean_subtracted_matrix = matrix - matrix.mean(axis=1, keepdims=True)
print("58.\n",mean_subtracted_matrix)

# 59. How to sort an array by the nth column?
array = np.random.randint(0, 10, (3, 3))
sorted_array = array[array[:, 1].argsort()]
print("59.\n",sorted_array)

# 60. How to tell if a given 2D array has null columns?
array = np.array([[1, 2, 3], [0, 0, 0], [4, 5, 6]])
null_columns = np.any(array.max(axis=0) == 0)
print("60.\n",null_columns)


51.
 [((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))]
52.
 [[0.         0.49121209 0.18060325 ... 0.87426988 0.20536549 0.79277409]
 [0.49121209 0.         0.33671652 ... 0.73837871 0.4235305  0.53161277]
 [0.18060325 0.33671652 0.         ... 0.72818514 0.25929766 0.62101074]
 ...
 [0.87426988 0.73837871 0.72818514 ... 0.         0.98330653 0.25261259]
 [0.20536549 0.4235305  0.25929766 ... 0.98330653 0.         0.85280759]
 [0.79277409 0.53161277 0.62101074 ... 0.25261259 0.85280759 0.        ]]
53.
 [1069547520 1076677837 1081711002]
55.
 (0,) 1
55.
 (1,) 2
55.
 (2,) 3
55.
 (3,) 4
55.
 (4,) 5
56.
 [[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81

In [1]:
import numpy as np

# 61. Find the nearest value from a given value in an array
def nearest_value(arr, value):
    index = np.abs(arr - value).argmin()
    return arr[index]

# Example
arr61 = np.array([1, 3, 5, 7, 9])
value61 = 6
result61 = nearest_value(arr61, value61)
print(f"61. Nearest value to {value61} in {arr61}: {result61}\n")

# 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?
arr62_1 = np.array([[1, 2, 3]])
arr62_2 = np.array([[4], [5], [6]])
iterator_sum = np.nditer([arr62_1, arr62_2, None])
for x, y, z in iterator_sum:
    z[...] = x + y
result62 = iterator_sum.operands[2]
print(f"62. Sum of {arr62_1} and {arr62_2} using iterator: {result62}\n")

# 63. Create an array class that has a name attribute
class NamedArray(np.ndarray):
    def __new__(cls, array, name="Unnamed"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

# Example
arr63 = NamedArray([1, 2, 3], name="ExampleArray")
print(f"63. NamedArray: {arr63.name} - {arr63}\n")

# 64. Consider a given vector, how to add 1 to each element indexed by a second vector
vector64 = np.array([1, 2, 3, 4, 5])
indices64 = np.array([1, 3, 1, 4, 2])
vector64[indices64] += 1
print(f"64. Updated vector: {vector64}\n")

# 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)
X65 = np.array([1, 2, 3, 4, 5])
I65 = np.array([1, 3, 1, 4, 2])
F65 = np.bincount(I65, weights=X65)
print(f"65. Accumulated array: {F65}\n")

# 66. Considering a (w, h, 3) image of (dtype=ubyte), compute the number of unique colors
image66 = np.random.randint(0, 256, size=(100, 100, 3), dtype=np.uint8)
unique_colors66 = len(np.unique(image66.reshape(-1, 3), axis=0))
print(f"66. Number of unique colors: {unique_colors66}\n")

# 67. Considering a four dimensions array, how to get sum over the last two axis at once
array67 = np.random.rand(2, 3, 4, 5)
sum_last_two_axes67 = np.sum(array67, axis=(-2, -1))
print(f"67. Sum over the last two axes: {sum_last_two_axes67}\n")

# 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of the same size describing subset indices
D68 = np.array([1, 2, 3, 4, 5])
S68 = np.array([0, 0, 1, 1, 2])
means68 = np.bincount(S68, weights=D68) / np.bincount(S68)
print(f"68. Means of subsets: {means68}\n")

# 69. How to get the diagonal of a dot product
A69 = np.random.rand(3, 3)
B69 = np.random.rand(3, 3)
diagonal_dot_product69 = np.diag(np.dot(A69, B69))
print(f"69. Diagonal of the dot product: {diagonal_dot_product69}\n")

# 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value
vector70 = np.array([1, 2, 3, 4, 5])
new_vector70 = np.zeros(len(vector70) + 3 * (len(vector70) - 1))
new_vector70[::4] = vector70
print(f"70. New vector: {new_vector70}")


61. Nearest value to 6 in [1 3 5 7 9]: 5

62. Sum of [[1 2 3]] and [[4]
 [5]
 [6]] using iterator: [[5 6 7]
 [6 7 8]
 [7 8 9]]

63. NamedArray: ExampleArray - [1 2 3]

64. Updated vector: [1 3 4 5 6]

65. Accumulated array: [0. 4. 5. 2. 4.]

66. Number of unique colors: 9999

67. Sum over the last two axes: [[11.37266075  9.05688965 11.38835939]
 [ 8.75089485  9.98645742  9.37908134]]

68. Means of subsets: [1.5 3.5 5. ]

69. Diagonal of the dot product: [0.72093254 0.73492747 0.8227226 ]

70. New vector: [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [6]:
import numpy as np

# Question 71
arr_3d = np.random.random((5, 5, 3))
arr_2d = np.random.random((5, 5))
result_71 = arr_3d * arr_2d[:, :, np.newaxis]

# Question 72
arr_swap_rows = np.random.random((5, 5))
arr_swap_rows[[0, 1]] = arr_swap_rows[[1, 0]]
result_72 = arr_swap_rows

# Question 73
triplets = np.random.randint(0, 10, (10, 3))
lines = set(tuple(sorted(pair)) for triplet in triplets for pair in zip(triplet, triplet[1:] + triplet[:1]))
result_73 = np.array(list(lines))

# Question 74
C = np.bincount([1, 1, 2, 3, 4, 4, 6])
A = np.repeat(np.arange(len(C)), C)
result_74 = A

# Question 75
arr_avg = np.arange(10)
window_size = 3
result_75 = np.convolve(arr_avg, np.ones(window_size)/window_size, mode='valid')

# Question 76
Z = np.arange(10)
result_76 = np.lib.stride_tricks.sliding_window_view(Z, (3,))

# Question 77
bool_value = True
float_value = -3.14
result_77 = np.logical_not(bool_value), -float_value

# # Question 78
# P0 = np.array([[0, 0], [1, 1], [2, 2]])
# P1 = np.array([[4, 4], [3, 3], [2, 2]])
# p = np.array([1, 1])
# distances = np.abs(np.cross(P1 - P0, P0 - p) / np.linalg.norm(P1 - P0, axis=1))

# Question 79
P = np.array([[1, 1], [2, 2], [3, 3]])
distances_79 = np.abs(np.cross(P1[:, np.newaxis] - P0[:, np.newaxis], P0[:, np.newaxis] - P) / np.linalg.norm(P1[:, np.newaxis] - P0[:, np.newaxis], axis=2))

# Question 80
def extract_subpart(arr, shape, center):
    slices = [slice(max(0, c - s // 2), min(d, c + (s + 1) // 2)) for c, s, d in zip(center, shape, arr.shape)]
    return arr[slices]

# arr_arbitrary = np.random.random((10, 10, 10))
# shape_subpart = (3, 3, 3)
# center_subpart = (5, 5, 5)
# result_80 = extract_subpart(arr_arbitrary, shape_subpart, center_subpart)

# Print results
print(f"71. Result: {result_71}")
print(f"72. Result: {result_72}")
print(f"73. Result: {result_73}")
print(f"74. Result: {result_74}")
print(f"75. Result: {result_75}")
print(f"76. Result: {result_76}")
print(f"77. Result: {result_77}")
print(f"78. Result: {distances}")
print(f"79. Result: {distances_79}")
# print(f"80. Result: {result_80}")


71. Result: [[[0.09762104 0.05108999 0.04716837]
  [0.60527146 0.35719837 0.15715043]
  [0.50651228 0.52617657 0.81002098]
  [0.51761294 0.29685889 0.7022507 ]
  [0.31050972 0.11762991 0.30435841]]

 [[0.24676075 0.0812016  0.72122982]
  [0.01470268 0.27294051 0.27534708]
  [0.10471498 0.29390655 0.19832089]
  [0.72353052 0.40336383 0.45275172]
  [0.24388614 0.32955671 0.0635419 ]]

 [[0.39917732 0.17891248 0.15834663]
  [0.28513086 0.47483615 0.45935428]
  [0.07006382 0.11036079 0.07404756]
  [0.26135263 0.09591871 0.12521999]
  [0.54624586 0.25873655 0.18631499]]

 [[0.18255577 0.37175582 0.1086811 ]
  [0.25173931 0.01850795 0.06518763]
  [0.02609242 0.01568056 0.01738953]
  [0.41812832 0.362569   0.01493821]
  [0.17489219 0.44699944 0.52662163]]

 [[0.50093531 0.69224604 0.79203379]
  [0.02179148 0.26525086 0.10662357]
  [0.09399413 0.07914234 0.14077095]
  [0.03466323 0.18917593 0.00665259]
  [0.57388417 0.54711321 0.61060481]]]
72. Result: [[0.8799201  0.6182323  0.5314839  0.2655

/tmp/ipykernel_3600/750933497.py:45: RuntimeWarning: invalid value encountered in divide
  distances_79 = np.abs(np.cross(P1[:, np.newaxis] - P0[:, np.newaxis], P0[:, np.newaxis] - P) / np.linalg.norm(P1[:, np.newaxis] - P0[:, np.newaxis], axis=2))


In [7]:
import numpy as np

# 81. Generate array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
R = np.lib.stride_tricks.as_strided(Z, (11, 4), (4, 4))
print("81. Result R:\n", R)

# 82. Compute matrix rank
# Create a random matrix
matrix = np.random.randint(0, 10, (5, 5))
rank = np.linalg.matrix_rank(matrix)
print("82. Matrix Rank:", rank)

# 83. Find the most frequent value in an array
arr = np.array([1, 2, 3, 1, 2, 3, 3, 3, 3])
most_frequent = np.bincount(arr).argmax()
print("83. Most Frequent Value:", most_frequent)

# 84. Extract all contiguous 3x3 blocks from a random 10x10 matrix
matrix = np.random.randint(0, 10, (10, 10))
blocks = np.lib.stride_tricks.as_strided(matrix, shape=(8, 8, 3, 3), strides=matrix.strides * 2)
print("84. Contiguous 3x3 Blocks:\n", blocks)

# 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]
class SymmetricArray(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super(SymmetricArray, self).__setitem__((i, j), value)
        super(SymmetricArray, self).__setitem__((j, i), value)

Z = SymmetricArray((3, 3))
Z[0, 1] = 1
print("85. Symmetric Array Z:\n", Z)

# 86. Compute the sum of p matrix products at once
p = 3
n = 4
matrices = [np.random.randint(0, 10, (n, n)) for _ in range(p)]
vectors = [np.random.randint(0, 10, (n, 1)) for _ in range(p)]
result = sum(np.dot(matrix, vector) for matrix, vector in zip(matrices, vectors))
print("86. Sum of Matrix Products:\n", result)

# 87. Get the block-sum (block size is 4x4) of a 16x16 array
arr = np.random.randint(0, 10, (16, 16))
block_sum = np.add.reduceat(np.add.reduceat(arr, np.arange(0, arr.shape[0], 4), axis=0), np.arange(0, arr.shape[1], 4), axis=1)
print("87. Block-Sum:\n", block_sum)

# 88. Implement the Game of Life using numpy arrays
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N == 3) & (Z[1:-1,1:-1] == 0)
    survive = ((N == 2) | (N == 3)) & (Z[1:-1,1:-1] == 1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0, 2, (50, 50))
for i in range(100): Z = iterate(Z)
print("88. Game of Life (After 100 Iterations):\n", Z)

# 89. Get the n largest values of an array
arr = np.random.randint(0, 100, 10)
n_largest_indices = np.argsort(arr)[-3:]
n_largest_values = arr[n_largest_indices]
print("89. N Largest Values:", n_largest_values)

# 90. Build the cartesian product of an arbitrary number of vectors
vectors = [np.array([1, 2, 3]), np.array([4, 5]), np.array([6, 7, 8])]
cartesian_product = np.array(np.meshgrid(*vectors)).T.reshape(-1, len(vectors))
print("90. Cartesian Product:\n", cartesian_product)


81. Result R:
 [[          1  8589934592           2 12884901888]
 [ 8589934592           2 12884901888           3]
 [          2 12884901888           3 17179869184]
 [12884901888           3 17179869184           4]
 [          3 17179869184           4 21474836480]
 [17179869184           4 21474836480           5]
 [          4 21474836480           5 25769803776]
 [21474836480           5 25769803776           6]
 [          5 25769803776           6 30064771072]
 [25769803776           6 30064771072           7]
 [          6 30064771072           7 34359738368]]
82. Matrix Rank: 5
83. Most Frequent Value: 3
84. Contiguous 3x3 Blocks:
 [[[[4 0 4]
   [3 0 3]
   [7 1 6]]

  [[0 4 1]
   [0 3 5]
   [1 6 0]]

  [[4 1 0]
   [3 5 6]
   [6 0 0]]

  [[1 0 9]
   [5 6 0]
   [0 0 2]]

  [[0 9 7]
   [6 0 1]
   [0 2 3]]

  [[9 7 1]
   [0 1 9]
   [2 3 4]]

  [[7 1 3]
   [1 9 2]
   [3 4 0]]

  [[1 3 0]
   [9 2 7]
   [4 0 0]]]


 [[[3 0 3]
   [7 1 6]
   [7 2 7]]

  [[0 3 5]
   [1 6 0]
   [2 7 7]

In [11]:
import numpy as np

# 91. Create a record array from a regular array
regular_array = np.array([(1, 2, 3), (4, 5, 6)])
record_array = np.core.records.fromarrays(regular_array.T, names='col1, col2, col3')
print("Record Array:")
print(record_array)

# 92. Compute Z to the power of 3 using 3 different methods
Z = np.arange(1, 6)
method1 = np.power(Z, 3)
method2 = Z ** 3
method3 = np.einsum('i,i,i->i', Z, Z, Z)
print("Z to the power of 3 using Method 1:", method1)
print("Z to the power of 3 using Method 2:", method2)
print("Z to the power of 3 using Method 3:", method3)

# # 93. Find rows of A that contain elements of each row of B
# A = np.random.randint(0, 10, (8, 3))
# B = np.random.randint(0, 10, (2, 2))
# rows = np.array([np.where((A == row[:, None]).all(-1))[0] for row in B])
# print("Rows of A that contain elements of each row of B:")
# print(rows)

# 94. Extract rows with unequal values from a 10x3 matrix
matrix = np.random.randint(0, 5, (10, 3))
unequal_rows = matrix[np.any(matrix[:, 1:] != matrix[:, :-1], axis=1)]
print("Rows with unequal values:")
print(unequal_rows)

# 95. Convert a vector of ints into a matrix binary representation
vector = np.array([1, 2, 3])
matrix_binary = (vector[:, None] & (1 << np.arange(8))) > 0
print("Matrix binary representation:")
print(matrix_binary.astype(int))

# 96. Extract unique rows from a two dimensional array
array = np.random.randint(0, 2, (5, 3))
unique_rows = np.unique(array, axis=0)
print("Unique rows:")
print(unique_rows)

# 97. Einsum equivalent of inner, outer, sum, and mul function for vectors A & B
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
inner = np.einsum('i,i', A, B)
outer = np.einsum('i,j->ij', A, B)
sum_ab = np.einsum('i->', A)
mul_ab = np.einsum('i,i->i', A, B)
print("Einsum equivalent of inner:", inner)
print("Einsum equivalent of outer:")
print(outer)
print("Einsum equivalent of sum:", sum_ab)
print("Einsum equivalent of mul:", mul_ab)

# 98. Sample a path described by two vectors (X, Y) using equidistant samples
X = np.linspace(0, 1, 10)
Y = np.sin(X)
num_samples = 5
samples_indices = np.linspace(0, len(X) - 1, num_samples).astype(int)
sampled_path = (X[samples_indices], Y[samples_indices])
print("Sampled path using equidistant samples:")
print(sampled_path)

# 99. Select rows from X that sum to n (multinomial distribution)
n = 10
X = np.random.randint(0, 5, (5, 3))
selected_rows = X[(X.sum(axis=1) == n)]
print("Rows from X that sum to n (multinomial distribution):")
print(selected_rows)

# 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X
N = 1000
X = np.random.randn(N)
means = [np.mean(np.random.choice(X, N)) for _ in range(N)]
confidence_interval = np.percentile(means, [2.5, 97.5])
print("Bootstrapped 95% confidence intervals for the mean of X:")
print(confidence_interval)


Record Array:
[(1, 2, 3) (4, 5, 6)]
Z to the power of 3 using Method 1: [  1   8  27  64 125]
Z to the power of 3 using Method 2: [  1   8  27  64 125]
Z to the power of 3 using Method 3: [  1   8  27  64 125]
Rows with unequal values:
[[4 4 2]
 [1 2 2]
 [0 2 1]
 [2 1 4]
 [4 0 0]
 [2 0 3]
 [2 4 2]
 [4 1 2]
 [0 4 1]
 [1 0 3]]
Matrix binary representation:
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]]
Unique rows:
[[0 0 1]
 [0 1 0]
 [1 0 1]]
Einsum equivalent of inner: 32
Einsum equivalent of outer:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Einsum equivalent of sum: 6
Einsum equivalent of mul: [ 4 10 18]
Sampled path using equidistant samples:
(array([0.        , 0.22222222, 0.44444444, 0.66666667, 1.        ]), array([0.        , 0.22039774, 0.42995636, 0.6183698 , 0.84147098]))
Rows from X that sum to n (multinomial distribution):
[]
Bootstrapped 95% confidence intervals for the mean of X:
[0.00987721 0.13908492]
